export const SET_USER_TYPE = 'SET_USER_TYPE';
export const ADD_USER_CHOICES = 'ADD_USER_CHOICES';
export const UPDATE_CURRENT_PATH = 'UPDATE_CURRENT_PATH';
export const ADD_USER_INFORMATION = 'ADD_USER_INFORMATION';
export const ADD_USER_AVAILABILITY = 'ADD_USER_AVAILABILITY';
export const ADD_SELECTED_SERVICE = 'ADD_SELECTED_SERVICE';
export const UPDATE_SERVICES = 'UPDATE_SERVICES';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
