export const ADD_SELECTED_SERVICE = 'ADD_SELECTED_SERVICE';
export const UPDATE_SERVICES = 'UPDATE_SERVICES';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const ADD_RESPONSES = 'ADD_RESPONSES';
export const UPDATE_RESPONSES = 'UPDATE_RESPONSES';
